let curriculum=[],courses=[],lessonCache=new Map(),quizCache=new Map(),advancedQuizCache=new Map(),currentLesson=0;
const COURSE_GROUP_STATE_KEY="fnpQuestCourseGroups";
async function loadJson(path){const response=await fetch(path,{cache:"no-store"});if(!response.ok)throw new Error("Could not load "+path);return response.json();}
function escapeCurriculumText(value){return String(value||"").replace(/[&<>\"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));}
function courseGroupState(){try{const saved=JSON.parse(localStorage.getItem(COURSE_GROUP_STATE_KEY)||"{}");return saved&&typeof saved==="object"&&!Array.isArray(saved)?saved:{};}catch(error){return {};}}
function isCourseExpanded(courseId){return courseGroupState()[courseId]===true;}
function saveCourseGroupState(state){try{localStorage.setItem(COURSE_GROUP_STATE_KEY,JSON.stringify(state));}catch(error){console.warn("Could not save course group state",error);}}
function toggleCourseGroup(courseId){const state=courseGroupState();state[courseId]=!isCourseExpanded(courseId);saveCourseGroupState(state);renderCurriculum();}
function showDataLoadError(error){console.error(error);const list=document.getElementById("curriculumList");if(list)list.innerHTML='<div class="card"><h3>Course content could not load</h3><p class="small">Please check your connection and reload the app.</p></div>';}
async function loadCurriculum(){try{const data=await loadJson("data/curriculum.json");if(!Array.isArray(data.lessons)||!data.lessons.length)throw new Error("Curriculum contains no lessons");curriculum=data.lessons;courses=Array.isArray(data.courses)&&data.courses.length?data.courses:[{id:"curriculum",title:"Curriculum",description:"",lessonIds:curriculum.map(item=>item.id)}];renderCurriculum();if(typeof renderAdvancedHub==="function")renderAdvancedHub();}catch(error){showDataLoadError(error);}}
function curriculumCard(item){const index=curriculum.indexOf(item);return '<div class="card mission"><div><h3>'+item.cardTitle+'</h3><p>'+item.summary+'</p></div><button onclick="startLesson('+index+')">Learn</button></div>';}
function renderCourseGroup(course,items){const expanded=isCourseExpanded(course.id),countLabel=items.length+" lesson"+(items.length===1?"":"s"),description=course.description?'<p class="small">'+escapeCurriculumText(course.description)+'</p>':"",instruction=expanded?"Tap to collapse":"Tap to expand";return '<section class="course-group"><button class="course-toggle" type="button" aria-expanded="'+expanded+'" onclick="toggleCourseGroup(\''+course.id+'\')"><span><strong>'+escapeCurriculumText(course.title)+'</strong><span class="small course-toggle-meta">'+countLabel+' · '+instruction+'</span></span><span class="course-chevron" aria-hidden="true">'+(expanded?"⌃":"⌄")+'</span></button><div class="course-content"'+(expanded?"":" hidden")+'>'+description+items.map(curriculumCard).join("")+'</div></section>';}
function renderCurriculum(){const list=document.getElementById("curriculumList");if(!list)return;const itemsById=new Map(curriculum.map(item=>[item.id,item])),assignedIds=new Set();const grouped=courses.map(course=>{const items=(Array.isArray(course.lessonIds)?course.lessonIds:[]).map(id=>itemsById.get(id)).filter(Boolean);items.forEach(item=>assignedIds.add(item.id));return items.length?renderCourseGroup(course,items):"";}).join("");const ungrouped=curriculum.filter(item=>!assignedIds.has(item.id));const extraCourse={id:"additional-lessons",title:"Additional Lessons",description:""};list.innerHTML=grouped+(ungrouped.length?renderCourseGroup(extraCourse,ungrouped):"");const loaded=document.getElementById("loadedLessons");if(loaded)loaded.textContent="Lessons 1–"+curriculum.length+" ✅";}
async function getLesson(index){const item=curriculum[index];if(!item)throw new Error("Unknown lesson index "+index);if(!lessonCache.has(item.id))lessonCache.set(item.id,loadJson(item.lessonFile));return lessonCache.get(item.id);}
async function getLessonQuiz(index){const item=curriculum[index];if(!item)throw new Error("Unknown quiz index "+index);if(!quizCache.has(item.id))quizCache.set(item.id,loadJson(item.quizFile));return quizCache.get(item.id);}
async function getAdvancedQuiz(index){const item=curriculum[index];if(!item?.advancedQuizFile)throw new Error("No advanced quiz for lesson index "+index);if(!advancedQuizCache.has(item.id))advancedQuizCache.set(item.id,loadJson(item.advancedQuizFile));return advancedQuizCache.get(item.id);}
async function startLesson(index){if(typeof learningAccessGranted!=="undefined"&&!learningAccessGranted){showAccessGate("Sign in with a registered email before opening lessons.");return;}if(!curriculum.length){toast("Course content is still loading. Please try again in a moment.");return;}currentLesson=index;if(!openPage("lesson"))return;const target=document.getElementById("lessonBody");target.innerHTML='<p class="small">Loading lesson…</p>';try{const lesson=await getLesson(index);target.innerHTML=lesson.html+'<div class="content-safety"><b>Educational use only.</b> Verify current guidelines, local policy, and official prescribing information. Do not use FNP Quest for decisions about an actual patient. <button class="inline-link" onclick="openPage(\'terms\')">Full disclaimer</button></div><div style="margin-top:16px"><button onclick="startLessonQuiz('+index+')">Start This Lesson Quiz →</button></div>';if(typeof trackAnonymousEvent==="function")trackAnonymousEvent("lesson_open",index+1);}catch(error){console.error(error);target.innerHTML='<p>Lesson content could not load. Please reload and try again.</p>';}}
