let practiceList=[],qi=0,practiceScore=0,practiceLoading=false,lqLesson=0,lqi=0,lqScore=0,lqQuestion=null;
function shuffleList(items){const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;}
function toTuple(question){const choices=shuffleList(question.choices.map((choice,index)=>({choice,correct:index===question.correctIndex})));return [question.question,choices.map(item=>item.choice),choices.findIndex(item=>item.correct),question.explanation];}
function setPracticeLoading(loading){practiceLoading=loading;const homeButton=document.getElementById("dailyPracticeBtn"),navButton=document.getElementById("navPracticeBtn");if(homeButton){homeButton.disabled=loading;homeButton.textContent=loading?"Loading…":"Start";homeButton.setAttribute("aria-busy",String(loading));}if(navButton){navButton.disabled=loading;navButton.innerHTML=loading?"⏳<br>Loading":"🩺<br>Practice";navButton.setAttribute("aria-busy",String(loading));}}
async function startPractice(){if(typeof learningAccessGranted!=="undefined"&&!learningAccessGranted){showAccessGate("Sign in with a registered email before starting practice.");return;}if(practiceLoading)return;if(!curriculum.length){toast("Course content is still loading. Please try again in a moment.");return;}setPracticeLoading(true);try{const quizzes=await Promise.all(curriculum.map((_,index)=>getLessonQuiz(index)));const all=quizzes.flatMap((quiz,index)=>quiz.questions.map(question=>["Lesson "+(index+1),...toTuple(question)]));practiceList=shuffleList(all).slice(0,10);qi=0;practiceScore=0;openPage("practice");renderQ();}catch(error){console.error(error);toast("Practice questions could not load. Please try again.");}finally{setPracticeLoading(false);}}
function renderQ(){const q=practiceList[qi];document.getElementById("qnum").textContent=qi+1;document.getElementById("qtotal").textContent=practiceList.length;document.getElementById("qtext").textContent=q[1];const options=document.getElementById("options");options.innerHTML="";document.getElementById("explain").style.display="none";document.getElementById("next").style.display="none";q[2].forEach((choice,index)=>{const button=document.createElement("button");button.className="option";button.textContent=String.fromCharCode(65+index)+". "+choice;button.onclick=()=>answer(button,index);options.appendChild(button);});}
function answer(button,index){const q=practiceList[qi],correct=index===q[3];document.querySelectorAll("#options .option").forEach(option=>option.disabled=true);button.classList.add(correct?"correct":"wrong");document.querySelectorAll("#options .option")[q[3]].classList.add("correct");const explain=document.getElementById("explain");explain.style.display="block";explain.innerHTML=(correct?"<b>✅ Correct!</b>":"<b>❌ Incorrect.</b>")+"<br><b>Correct answer: "+String.fromCharCode(65+q[3])+". "+q[2][q[3]]+"</b><br><br>"+q[4];if(correct){practiceScore++;addXP(20);}else{state.mistakes.push({topic:q[0],q:q[1],correct:q[2][q[3]],why:q[4]});save();}document.getElementById("next").style.display="inline-block";}
function nextQ(){if(qi<practiceList.length-1){qi++;renderQ();}else{addXP(80);markStudyDay();recordQuizResult(0,practiceScore,practiceList.length);if(typeof trackAnonymousEvent==="function")trackAnonymousEvent("practice_complete");save();toast(streakMessage());setTimeout(()=>openPage("home"),900);}}
async function startLessonQuiz(index){if(typeof learningAccessGranted!=="undefined"&&!learningAccessGranted){showAccessGate("Sign in with a registered email before starting a quiz.");return;}lqLesson=index;lqi=0;lqScore=0;openPage("lessonQuiz");try{await getLessonQuiz(index);await renderLQ();if(typeof trackAnonymousEvent==="function")trackAnonymousEvent("lesson_quiz_start",index+1);}catch(error){console.error(error);toast("Lesson quiz could not load. Please try again.");}}
async function renderLQ(){const quiz=await getLessonQuiz(lqLesson);lqQuestion=toTuple(quiz.questions[lqi]);const q=lqQuestion;document.getElementById("lqnum").textContent=lqi+1;document.getElementById("lqtotal").textContent=quiz.questions.length;document.getElementById("lqtext").textContent=q[0];const box=document.getElementById("lqoptions");box.innerHTML="";document.getElementById("lqexplain").style.display="none";document.getElementById("lqnext").style.display="none";q[1].forEach((answer,index)=>{const button=document.createElement("button");button.className="option";button.textContent=String.fromCharCode(65+index)+". "+answer;button.onclick=()=>answerLQ(button,index);box.appendChild(button);});}
async function answerLQ(button,index){const q=lqQuestion,correct=index===q[2];document.querySelectorAll("#lqoptions .option").forEach(option=>option.disabled=true);button.classList.add(correct?"correct":"wrong");document.querySelectorAll("#lqoptions .option")[q[2]].classList.add("correct");const explain=document.getElementById("lqexplain");explain.style.display="block";explain.innerHTML=(correct?"<b>✅ Correct!</b>":"<b>❌ Incorrect.</b>")+"<br><b>Correct answer: "+String.fromCharCode(65+q[2])+". "+q[1][q[2]]+"</b><br><br>"+q[3];if(correct){lqScore++;addXP(20);}else{state.mistakes.push({topic:"Lesson "+(lqLesson+1),q:q[0],correct:q[1][q[2]],why:q[3]});save();}document.getElementById("lqnext").style.display="inline-block";}
async function nextLQ(){const quiz=await getLessonQuiz(lqLesson);if(lqi<quiz.questions.length-1){lqi++;renderLQ();}else{if(!state.completed.includes(lqLesson)){state.completed.push(lqLesson);addXP(50);}markStudyDay();recordQuizResult(lqLesson+1,lqScore,quiz.questions.length);if(typeof trackAnonymousEvent==="function")trackAnonymousEvent("lesson_quiz_complete",lqLesson+1);save();toast(streakMessage());setTimeout(()=>openPage("home"),900);}}
